import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/BlogsContent.module.css";
import NavBar from "./Component/NavBar";
import sliderImage from "../public/sliderImg.png";
import blogImage from "../public/blogContentImage.png";
import Form from "./Component/Form";

import { useRouter } from "next/router";

const BlogsContent = () => {
  const blogData = [
    {
      title: "The Symbiotic Evolution of Technology and AI",
      info: "In a world where technology is advancing at an exponential pace,one of the most intriguing and transformative frontiers is therealm of Artificial Intelligence (AI). AI, often referred to as the pinnacle of technological evolution, has been revolutionizing industries and reshaping the way we interactwith our environment. This symbiotic relationship betweentechnology and AI is not only pushing boundaries but also promising a future that was once the realm of science fiction",
      imgUrl: blogImage,
    },
    {
      title: "The Symbiotic Evolution of Technology and AI2",
      info: "In a world where technology is advancing at an exponential pace,one of the most intriguing and transformative frontiers is therealm of Artificial Intelligence (AI). AI, often referred to as the pinnacle of technological evolution, has been revolutionizing industries and reshaping the way we interactwith our environment. This symbiotic relationship betweentechnology and AI is not only pushing boundaries but also promising a future that was once the realm of science fiction",
      imgUrl: blogImage,
    },
    {
      title: "The Symbiotic Evolution of Technology and AI3",
      info: "In a world where technology is advancing at an exponential pace,one of the most intriguing and transformative frontiers is therealm of Artificial Intelligence (AI). AI, often referred to as the pinnacle of technological evolution, has been revolutionizing industries and reshaping the way we interactwith our environment. This symbiotic relationship betweentechnology and AI is not only pushing boundaries but also promising a future that was once the realm of science fiction",
      imgUrl: blogImage,
    },
    {
      title: "The Symbiotic Evolution of Technology and AI",
      info: "In a world where technology is advancing at an exponential pace,one of the most intriguing and transformative frontiers is therealm of Artificial Intelligence (AI). AI, often referred to as the pinnacle of technological evolution, has been revolutionizing industries and reshaping the way we interactwith our environment. This symbiotic relationship betweentechnology and AI is not only pushing boundaries but also promising a future that was once the realm of science fiction",
      imgUrl: blogImage,
    },
  ];
  const [currentSlide, setCurrentSlide] = useState(0);

  const nextSlide = () => {
    const slider = document.querySelector(`.${styles.section3Box}`);
    const width = slider.offsetWidth;
    if (currentSlide < blogData.length - 1) {
      setCurrentSlide(currentSlide + 1);
      slider.scrollLeft += width; // Move to the next slide
    }
  };

  const prevSlide = () => {
    const slider = document.querySelector(`.${styles.section3Box}`);
    const width = slider.offsetWidth;
    if (currentSlide > 0) {
      setCurrentSlide(currentSlide - 1);
      slider.scrollLeft -= width; // Move to the previous slide
    }
  };

  return (
    <>
      <Head>
        <title>HYPENET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className={styles.section2}>
          <div className={styles.contentContainer}>
            <div className={styles.leftContainer}>
              <Image
                src="/gif2.gif"
                width={100}
                height={50}
                className={styles.topLftImg}
              />
              <div className={styles.header}>
                <h2>Blogs</h2>
              </div>
            </div>
            <div className={styles.rightContainer}>
              <Image
                src="/blogsImage.png"
                width={600}
                height={400}
                className={styles.blogsImage}
              />
            </div>
          </div>
        </section>
        <section className={styles.section3}>
          <div className={styles.section3Box}>
            {blogData.map((data, index) => (
              <div
                key={index}
                className={`${styles.slide} ${
                  index === currentSlide ? styles.active : ""
                }`}
              >
                <h3>{data.title}</h3>
                <div className={styles.infoText}>
                  <p>{data.info}</p>
                </div>
                <div className={styles.imageContainer}>
                  <Image
                    src={data.imgUrl.src}
                    width={400}
                    height={100}
                    className={styles.sliderImg}
                  />

                  <div className={styles.leftArrow}>
                    <Image
                      src="/mainBlogArrow.png"
                      width={80}
                      height={80}
                      className={styles.ImgContent}
                      onClick={prevSlide}
                    />
                    <p>The main Blog</p>
                  </div>
                  <div className={styles.rightArrow}>
                    <Image
                      src="/nextBlogArrow.png"
                      width={80}
                      height={80}
                      className={styles.ImgContent}
                      onClick={nextSlide}
                    />
                    <p>Next blog</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
        <Form />
      </main>
    </>
  );
};

export default BlogsContent;
