import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Blogs.module.css";
import NavBar from "./Component/NavBar";
import sliderImage from "../public/sliderImg.png";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import Form from "./Component/Form";
import { useRouter } from "next/router";

const Blogs = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [showLeftArrow, setShowLeftArrow] = useState(false);
  const [showRightArrow, setShowRightArrow] = useState(true);

  const router = useRouter();
  const handleNavigate = (path) => {
    router.push(path);
  };

  const handleNextSlide = () => {
    const slider = document.querySelector(`.${styles.sliderContainer}`);
    const width = slider.offsetWidth;
    slider.scrollLeft -= width;
  };

  const handlePrevSlide = () => {
    const slider = document.querySelector(`.${styles.sliderContainer}`);
    const width = slider.offsetWidth;
    slider.scrollLeft += width;
  };
  const sliderData = [
    {
      imgUrl: sliderImage,
      text: "The Symbiotic Evolution of Technology and AI",
    },
    {
      imgUrl: sliderImage,
      text: "The Symbiotic Evolution of Technology and AI",
    },
    {
      imgUrl: sliderImage,
      text: "The Symbiotic Evolution of Technology and AI",
    },
    {
      imgUrl: sliderImage,
      text: "The Symbiotic Evolution of Technology and AI",
    },
    {
      imgUrl: sliderImage,
      text: "The Symbiotic Evolution of Technology and AI",
    },
  ];

  return (
    <>
      <Head>
        <title>HYPENET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className={styles.section2}>
          <div className={styles.contentContainer}>
            <div className={styles.leftContainer}>
              <Image
                src="/gif2.gif"
                width={100}
                height={50}
                className={styles.topLftImg}
              />
              <div className={styles.header}>
                <h2>Blogs</h2>
              </div>
            </div>
            <div className={styles.rightContainer}>
              {/* <Image
                src="/blogsImage.png"
                width={600}
                height={400}
                className={styles.blogsImage}
              /> */}
            </div>
            <div className={styles.rightContainer}>
              <Image
                src="/blogsImage.png"
                width={600}
                height={400}
                className={styles.blogsImage}
              />
            </div>
          </div>
        </section>

        <section className={styles.section3}>
          <div className={styles.sliderContainer}>
            {sliderData.map((data, index) => (
              <div
                key={index}
                className={`${styles.outerBox} ${
                  index === currentSlide ? styles.activeSlide : ""
                }`}
                onClick={() => handleNavigate("/blogsContent")}
              >
                <p>{data.text}</p>
                <Image
                  src={sliderImage.src}
                  width={400}
                  height={250}
                  className={styles.sliderImg}
                />
              </div>
            ))}
          </div>
          <Image
            src="/leftArrow.png"
            width={50}
            height={50}
            className={styles.arrowBtn}
            onClick={handleNextSlide}
          />
          <Image
            src="/rightArrow.png"
            width={50}
            height={50}
            className={styles.arrowBtn2}
            onClick={handlePrevSlide}
          />
          <div className={styles.gradientbox}></div>
        </section>

        <Form />
      </main>
    </>
  );
};

export default Blogs;
