import { useState } from "react";

import styles from "@/styles/careers.module.css";
import Image from "next/image";
import Head from "next/head";
import NavBar from "./Component/NavBar";
import Form from "./Component/Form";

const Careers = () => {
  return (
    <>
      <Head>
        <title>HYPENET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />

        <section className={styles.section2Mob}>
          <div className={styles.contentContainer}>
            <div className={styles.rightContainer}>
              <Image
                src="/topLeftImg.png"
                width={100}
                height={50}
                className={styles.topLftImg}
              />
              <div className={styles.header}>
                <h2>SHINE BRIGHT WITH US</h2>
              </div>

              <Image
                src="/bottomRightImage.png"
                width={100}
                height={50}
                className={styles.bottmRightImg}
              />
            </div>
            <Image
              src="/carrerBanner.png"
              width={500}
              height={200}
              alt="banner"
              className={styles.banner}
            />
          </div>
        </section>

        <section className={styles.section2}>
          <div className={styles.bannerContainer}>
            <Image
              src="/carrerBanner.png"
              width={500}
              height={200}
              alt="banner"
              className={styles.banner}
            />
            <div className={styles.text}>
              <h2>SHINE BRIGHT WITH US</h2>
            </div>
          </div>
        </section>

        <section className={styles.section3}>
          <div className={styles.listContainer}>
            <div className={styles.headersTitle}>
              <h2>Open Positions</h2>
            </div>

            <div className={styles.titleBox}>
              <p>Job Title</p>
            </div>
            <div className={styles.titleBox2}>
              <p>Integration Developer</p>
              <button>View job</button>
            </div>
            <div className={styles.titleBox2}>
              <p>Open Application</p>
              <button>View job</button>
            </div>
            <div className={styles.titleBox2}>
              <p>Senior Backend Developer – C# / .Net / Azure</p>
              <button>View job</button>
            </div>
            <div className={styles.titleBox2}>
              <p>Test Automation Architect</p>
              <button>View job</button>
            </div>
          </div>
        </section>
        <Form />
      </main>
    </>
  );
};

export default Careers;
