import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import txtLogo from "../public/hypenetTxtLogo.png";
import digital from "../public/digitalLogo.png";
import devops from "../public/devopsLogo.png";
import product from "../public/productLogo.png";
import software from "../public/softwereLogo.png";
import banner from "../public/banner.png";
// import videoGraphic from "../public/video1.mp4";

import { useRouter } from "next/router";
import { useState } from "react";
import NavBar from "./Component/NavBar";
import Form from "./Component/Form";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [navMenu, setNavMenu] = useState(false);
  const gifData = [
    {
      para: "Our expert team understands your objectives and requirements,crafting tailored solutions through focused research, ideation,and design thinking, commitment and excellence.",
    },
    {
      para: "We create tailored business solutions in collaboration with our diverse team, ensuring clear communication throughout design and iterative development",
    },
    {
      para: "Our expert team understands your objectives and requirements,crafting tailored solutions through focused research, ideation,and design thinking, commitment and excellence.",
    },
  ];

  const gifDataMob = [
    {
      title: "DEFINE",
      para: "Our expert team understands your objectives and requirements,crafting tailored solutions through focused research, ideation,and design thinking, commitment and excellence.",
    },
    {
      title: "DESIGIN",
      para: "We create tailored business solutions in collaboration with our diverse team, ensuring clear communication throughout design and iterative development",
    },
    {
      title: "DELIVER",
      para: "Our expert team understands your objectives and requirements,crafting tailored solutions through focused research, ideation,and design thinking, commitment and excellence.",
    },
  ];

  const serviceData = [
    {
      imageUrl: digital,
      title: "Digital Transformation",
    },
    {
      imageUrl: devops,
      title: "DEV OPS",
    },
    {
      imageUrl: software,
      title: "Software Integration",
    },
    {
      imageUrl: product,
      title: "Product Engineering",
    },
    {
      imageUrl: product,
      title: "Product Engineering",
    },
    {
      imageUrl: product,
      title: "Product Engineering",
    },
  ];
  const router = useRouter();

  const handleNavigate = (path) => {
    router.push(path);
  };

  const showMenuBox = () => {
    setNavMenu(!navMenu);
  };

  return (
    <>
      <Head>
        <title>HYPENET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />

        <section className={styles.section2}>
          <div className={styles.contentContainer}>
            <Image
              src="/leftImage.png"
              width={500}
              height={200}
              className={styles.leftImage}
            />
            <div className={styles.rightContainer}>
            <Image
                src="/gif2.gif"
                width={100}
                height={50}
                className={styles.topLftImg}
              />
              {/* <Image
                src="/topLeftImg.png"
                width={100}
                height={50}
                className={styles.topLftImg}
              /> */}
              <div className={styles.header}>
                <h2>EMPOWERING BUSINESS EXCELLENCE</h2>
                <p>
                  Where AI, ML & Futuristic <br /> Tech Coverage!
                </p>
              </div>

             
            </div>
          </div>
        </section>

        <section className={styles.section3}>
          <div className={styles.section3CotentContainer}>
            <div className={styles.leftTextContent}>
              <h2>WHO WE ARE</h2>
              <div className={styles.paraBox}>
                <p>
                  Hypenet is an IT consulting and services organization with a
                  focus on software product development and digital
                  transformation solutions.
                </p>
              </div>
              <button>
                <span>Know more</span>
              </button>
            </div>

            <video
             width="500" height="600"
              className={styles.rightImage}
            
             autoPlay loop muted>
              <source src="/video1.mp4" type="video/mp4" />
            </video>

            {/* <Image
              src="/videoImage.png"
              width={500}
              height={200}
              className={styles.rightImage}
            /> */}
          </div>
        </section>
        <section className={styles.section4Mobile}>
          <div>
            <h2 className={styles.headerTags}>3</h2>
            <Image
              src="/giffCard.gif"
              width={100}
              height={100}
              alt="gif"
              className={styles.giffImages}
            />
          </div>
          <div className={styles.textContainer}>
            {gifDataMob.map((data, index) => (
              <div key={index} className={styles.textBox}>
                <h2>{data.title}</h2>
                <div className={styles.paraTxt}>
                  <p>{data.para}</p>
                </div>
              </div>
            ))}

            {/* <div></div>
            <div></div> */}
          </div>
        </section>

        <section4 className={styles.section4}>
          <div className={styles.leftContainer}>
            <div className={styles.topBox}></div>
            <div className={styles.middleBox}></div>
            <div className={styles.bottomBox}></div>

            <h2 className={styles.headerTag}>3</h2>

            <Image
              src="/giffCard.gif"
              width={100}
              height={100}
              alt="gif"
              className={styles.giffImage}
            />

            <div className={styles.label1}></div>
            <div className={styles.label2}></div>
            <p className={styles.para1}>EFINE</p>
            <p className={styles.para2}>ESIGN</p>
            <p className={styles.para3}>ELIVER</p>
          </div>

          <div className={styles.rightContainer}>
            <div className={styles.rightContainerBox}>
              {gifData.map((data, index) => (
                <div key={index} className={styles.paraText}>
                  <p>{data.para}</p>
                </div>
              ))}
            </div>
          </div>
        </section4>

        <section5 className={styles.section5}>
          <h2>SERVICES</h2>
          <div className={styles.productContainer}>
            {serviceData.map((data, index) => (
              <div key={index} className={styles.productBox}>
                <Image
                  src={data.imageUrl.src}
                  width={50}
                  height={50}
                  className={styles.productImage}
                  alt="image"
                />
                <div>
                  <h3>{data.title}</h3>
                </div>
              </div>
            ))}
          </div>
          <button className={styles.btn}> Know More</button>
        </section5>
        <div className={styles.clientBanner}>
          <Image
            src="/clientBanner.png"
            alt="client"
            width={1000}
            height={700}
            className={styles.clientImage}
          />
        </div>
        <Form />
        {/* <section className={styles.section6}>
          <div className={styles.footerContainer}>
            <div className={styles.menuContainer}>
              <h3>Menu</h3>
              <p onClick={() => handleNavigate("/about")}>About Us</p>
              <p onClick={() => handleNavigate("/services")}>Our Services</p>
              <p>Privicy Policy</p>
              <p onClick={() => handleNavigate("/careers")}>Careers</p>
              <div className={styles.mailContainer}>
                <p>SUBSCRIBE TO OUR NEWSLETTER</p>
                <form>
                  <div className={styles.inputContainer}>
                    <input placeholder="Enter your email here*" />
                    <button>Submit</button>
                  </div>
                </form>
                <p className={styles.section6Para}>
                  © 2023 by Hypenet Network Services L.L.C
                </p>
              </div>
            </div>
            <div className={styles.menuContainer2}>
              <h3>CONTACT US</h3>
              <p>Hypenet Network Services L.L.C</p>

              <div className={styles.iconContaner}>
                <Image
                  src="/phone.png"
                  width={50}
                  height={50}
                  className={styles.iconImage}
                  alt="icone"
                />
                <p>+971 56 778 6926 </p>
              </div>
              <div className={styles.iconContaner}>
                <Image
                  src="/mail.png"
                  width={50}
                  height={50}
                  className={styles.iconImage}
                  alt="icone"
                />
                <p>ello@hypenet.ae </p>
              </div>
              <div className={styles.iconContaner}>
                <div>
                  <Image
                    src="/map-pin.png"
                    width={50}
                    height={50}
                    className={styles.iconImage}
                    alt="icone"
                  />
                </div>

                <p>
                  Level 6B, Rolex Tower, Sheikh Zayed Road, Near Financial
                  Centre Metro, DIFC, Dubai - United Arab Emirates
                </p>
              </div>
              <div className={styles.mediaContainer}>
                <Image
                  src="/linkedInLogo.png"
                  width={100}
                  height={100}
                  alt="image"
                  className={styles.mediaImage}
                />
                <Image
                  src="/instaLogo.png"
                  width={100}
                  height={100}
                  alt="image"
                  className={styles.mediaImage}
                />
              </div>
            </div>

            <div className={styles.menuContainer3}>
              <h3>FOR ANY INFORMATION CONTACT US</h3>
              <form>
                <div className={styles.inputContainer2}>
                  <input placeholder="First Name*" />
                </div>
                <div className={styles.inputContainer2}>
                  <input placeholder="Last Name*" />
                </div>
                <div className={styles.inputContainer2}>
                  <input placeholder="Email*" />
                </div>
                <div className={styles.inputContainer2}>
                  <input placeholder="Mobile No*" />
                </div>
                <div className={styles.textAreaContainer}>
                  <textarea
                    placeholder="Enter your requirments*"
                    rows="5"
                    cols="50"
                  ></textarea>
                  <button>Submit</button>
                </div>
              </form>
            </div>
          </div>
        </section> */}
        {/* <section className={styles.section7}>
          <Image
            src="/webBanner.png"
            width={1000}
            height={300}
            alt="banner"
            className={styles.banner}
          />
        </section> */}
      </main>
    </>
  );
}
