import { useState } from "react";

import txtLogo from "../public/hypenetTxtLogo.png";

import Head from "next/head";
import digital from "../public/digitalLogo.png";
import devops from "../public/devopsLogo.png";
import product from "../public/productLogo.png";
import software from "../public/softwereLogo.png";

import banner from "../public/banner.png";
import cloudService from "../public/cloudService.png";
import microService from "../public/micriServiceLogo.png";
import thirdLogo from "../public/thirdParty.png";

import Image from "next/image";
import aiBot from "../public/GroupAi.png";
import aiMl from "../public/aiMl.png";
import dataSci from "../public/dataScience.png";
import iotLogo from "../public/iotLogo.png";

import styles from "@/styles/Services.module.css";
import NavBar from "./Component/NavBar";
import Form from "./Component/Form";

const Services = () => {
  const [openBox, setOpenBox] = useState(false);
  const [openbox2, setOpenBox2] = useState(false);
  const [openbox3, setOpenBox3] = useState(false);
  const [openbox4, setOpenBox4] = useState(false);

  const [activeIndex, setActiveIndex] = useState(null);

  const onItemClick = (index) => {
    setActiveIndex(index === activeIndex ? null : index);
    console.log("index", index);
  };

  const toggelContainer = () => {
    console.log("clicked");
    setOpenBox(!openBox);
  };
  const toggelContainer2 = () => {
    console.log("clicked");
    setOpenBox2(!openbox2);
  };
  const toggelContainer3 = () => {
    console.log("clicked");
    setOpenBox3(!openbox3);
  };
  const toggelContainer4 = () => {
    console.log("clicked");
    setOpenBox4(!openbox4);
  };
  const digitalArray = [
    {
      imageUrl: aiBot,
      title: "AI-BOT Development",
    },
    {
      imageUrl: aiMl,
      title: "AI/ML Development",
    },
    {
      imageUrl: dataSci,
      title: "Data Science",
    },
    {
      imageUrl: iotLogo,
      title: "IoT Development",
    },
  ];

  const softwareData = [
    {
      imgUrl: cloudService,
      title: "Cloud Services",
    },
    {
      imgUrl: microService,
      title: "Custom Microservices",
    },
    {
      imgUrl: thirdLogo,
      title: "Third Party Integrations",
    },
    {
      imgUrl: cloudService,
      title: "Cloud Services",
    },
  ];

  return (
    <>
      <Head>
        <title>HYPENET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className={styles.section2}>
          <div className={styles.contentContainer}>
            <Image
              src="/leftImage.png"
              width={500}
              height={200}
              className={styles.leftImage}
            />
            <div className={styles.rightContainer}>
              <Image
                src="/gif2.gif"
                width={100}
                height={50}
                className={styles.topLftImg}
              />
              <div className={styles.header}>
                <h2>Our Services</h2>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.section3}>
          <div className={styles.accordianBox}>
            <div className={styles.header}>
              <div
                className={`${styles.headerContainer} ${
                  openBox ? styles.open : ""
                }`}
                onClick={toggelContainer}
              >
                <h2>DIGITAL TRANSFORMATION</h2>
                {openBox && (
                  <div className={styles.digitalContainer}>
                    <div className={styles.logoConatiner}>
                      {digitalArray.map((data, index) => (
                        <div key={index} className={styles.imgTxtContainer}>
                          {console.log("hello", data)}
                          <Image
                            src={data.imageUrl.src}
                            width={50}
                            height={50}
                            className={styles.logoImage}
                            alt="image"
                          />
                          <div className={styles.logoTxt}>
                            <p>{data.title}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                    <Image
                      src="/bannerImage.png"
                      width={800}
                      height={500}
                      className={styles.logoBanner}
                      alt="banner"
                    />
                  </div>
                )}
              </div>
            </div>

            <div className={styles.header2}>
              <div
                className={`${styles.headerContainer} ${
                  openbox2 ? styles.open2 : ""
                }`}
                onClick={toggelContainer2}
              >
                <h2>SOFTWARE INTEGRATION</h2>
                {openbox2 && (
                  <div className={styles.digitalContainer2}>
                    <div className={styles.logoConatiner}>
                      {softwareData.map((data, index) => (
                        <div key={index} className={styles.imgTxtContainer}>
                          {console.log("software", data)}
                          <Image
                            src={data.imgUrl.src}
                            width={50}
                            height={50}
                            className={styles.logoImage}
                            alt="image"
                          />
                          <div className={styles.logoTxt2}>
                            <p>{data.title}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                    <Image
                      src="/bannerImage.png"
                      width={800}
                      height={500}
                      className={styles.logoBanner}
                      alt="banner"
                    />
                  </div>
                )}
              </div>
            </div>

            <div className={styles.header}>
              <div
                className={`${styles.headerContainer} ${
                  openbox3 ? styles.open : ""
                }`}
                onClick={toggelContainer3}
              >
                <h2>PROUDECT ENGINEER</h2>
                {openbox3 && (
                  <div className={styles.digitalContainer}>
                    <div className={styles.logoConatiner}>
                      {digitalArray.map((data, index) => (
                        <div key={index} className={styles.imgTxtContainer}>
                          {console.log("hello", data)}
                          <Image
                            src={data.imageUrl.src}
                            width={50}
                            height={50}
                            className={styles.logoImage}
                            alt="image"
                          />
                          <div className={styles.logoTxt}>
                            <p>{data.title}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                    <Image
                      src="/bannerImage.png"
                      width={800}
                      height={500}
                      className={styles.logoBanner}
                      alt="banner"
                    />
                  </div>
                )}
              </div>
            </div>

            <div className={styles.header2}>
              <div
                className={`${styles.headerContainer} ${
                  openbox4 ? styles.open2 : ""
                }`}
                onClick={toggelContainer4}
              >
                <h2>WEB & MOBILE</h2>
                {openbox4 && (
                  <div className={styles.digitalContainer2}>
                    <div className={styles.logoConatiner}>
                      {softwareData.map((data, index) => (
                        <div key={index} className={styles.imgTxtContainer}>
                          {console.log("software", data)}
                          <Image
                            src={data.imgUrl.src}
                            width={50}
                            height={50}
                            className={styles.logoImage}
                            alt="image"
                          />
                          <div className={styles.logoTxt2}>
                            <p>{data.title}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                    <Image
                      src="/bannerImage.png"
                      width={800}
                      height={500}
                      className={styles.logoBanner}
                      alt="banner"
                    />
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>
        <Form />
      </main>
    </>
  );
};

export default Services;
